version: 2
updates:
  - package-ecosystem: 'github-actions'
    directory: '/'
    # Every weekday
    schedule:
      interval: 'weekly'

  - package-ecosystem: 'docker'
    directory: '/backend'
    # Every weekday
    schedule:
      interval: 'weekly'
    # Ignore minor version updates (3.10 -> 3.11) but update patch versions
    ignore:
      - dependency-name: '*'
        update-types:
          - 'version-update:semver-major'
          - 'version-update:semver-minor'

  - package-ecosystem: 'docker'
    directory: '/traefik'
    # Every weekday
    schedule:
      interval: 'weekly'

  # Enable version updates for Python/Pip - Production
  - package-ecosystem: 'pip'
    # Look for a `requirements.txt` in the `root` directory
    # also 'setup.cfg', 'runtime.txt' and 'requirements/*.txt'
    directory: '/'
    # Every weekday
    schedule:
      interval: 'weekly'
