version: "3"

services:
  backend:
    container_name: dhanhq_ohlc_local
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "5005:5005"
    volumes:
      - ./backend:/app
    environment:
      PORT: 5005
    env_file:
      - .env
    command: /start-reload.sh
